"""add_employee_joined_at_and_status

Revision ID: 0c0c173a8317
Revises: 176f5886852c
Create Date: 2026-06-08 00:10:31.260074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0c173a8317'
down_revision: Union[str, None] = '176f5886852c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('joined_at', sa.DateTime(), nullable=True))
    op.add_column('employees', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'joined_at')
    # ### end Alembic commands ###
