"""add_generic_tracker_and_sync_config

Revision ID: 176f5886852c
Revises: a1b2c3d4e5f6
Create Date: 2026-06-07 13:03:59.847252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176f5886852c'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('epics', sa.Column('tracker_ref', sa.String(length=200), nullable=True))
    op.add_column('epics', sa.Column('tracker_url', sa.String(length=500), nullable=True))
    op.add_column('epics', sa.Column('tracker_type', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('sync_provider', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('sync_config', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('tracker_ref', sa.String(length=200), nullable=True))
    op.add_column('tasks', sa.Column('tracker_url', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('tracker_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'tracker_type')
    op.drop_column('tasks', 'tracker_url')
    op.drop_column('tasks', 'tracker_ref')
    op.drop_column('projects', 'sync_config')
    op.drop_column('projects', 'sync_provider')
    op.drop_column('epics', 'tracker_type')
    op.drop_column('epics', 'tracker_url')
    op.drop_column('epics', 'tracker_ref')
    # ### end Alembic commands ###
