"""recreate_guardrail_logs

Revision ID: 3cfcf02875f9
Revises: e9e285e42add
Create Date: 2026-06-09 10:25:47.922205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfcf02875f9'
down_revision: Union[str, None] = 'e9e285e42add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrail_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_guardrail_logs_project_id', 'guardrail_logs', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_guardrail_logs_project_id', table_name='guardrail_logs')
    op.drop_table('guardrail_logs')
    # ### end Alembic commands ###
