"""add_modules_json_to_projects

Revision ID: 5e51dc50954c
Revises: fba322396457
Create Date: 2026-06-08 02:27:58.905045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e51dc50954c'
down_revision: Union[str, None] = 'fba322396457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('modules_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'modules_json')
    # ### end Alembic commands ###
