"""add source fields to clarifications

Revision ID: d40caa69f6fa
Revises: 3cfcf02875f9
Create Date: 2026-06-11 14:18:57.817693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40caa69f6fa'
down_revision: Union[str, None] = '3cfcf02875f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clarifications', sa.Column('source_sentence', sa.Text(), nullable=True))
    op.add_column('clarifications', sa.Column('source_section', sa.String(length=200), nullable=True))
    op.add_column('clarifications', sa.Column('source_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clarifications', 'source_page')
    op.drop_column('clarifications', 'source_section')
    op.drop_column('clarifications', 'source_sentence')
    # ### end Alembic commands ###
