"""add_branding_settings

Revision ID: e9e285e42add
Revises: 466ced9bd536
Create Date: 2026-06-09 10:24:35.955225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e285e42add'
down_revision: Union[str, None] = '466ced9bd536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('prepared_by', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_guardrail_logs_project_id'), table_name='guardrail_logs')
    op.drop_table('guardrail_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrail_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('phase', sa.VARCHAR(length=100), nullable=False),
    sa.Column('layer', sa.INTEGER(), nullable=False),
    sa.Column('trigger', sa.VARCHAR(length=100), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardrail_logs_project_id'), 'guardrail_logs', ['project_id'], unique=False)
    op.drop_table('branding_settings')
    # ### end Alembic commands ###
