"""initial_schema

Revision ID: eca5b2e5babb
Revises: 
Create Date: 2026-06-06 20:13:03.236368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca5b2e5babb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_technologies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=False),
    sa.Column('availability_pct', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('historical_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('estimated_points', sa.Integer(), nullable=True),
    sa.Column('actual_points', sa.Integer(), nullable=True),
    sa.Column('duration_weeks', sa.Float(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('phase', sa.Enum('redaction', 'chat', 'techstack', 'team', 'estimation', 'epics', 'complete', name='projectphase'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'complete', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('clarifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('explicit', 'vague', 'missing_section', 'contradiction', name='tbdlevel'), nullable=False),
    sa.Column('status', sa.Enum('open', 'answered', 'tbd', 'oos', name='tbdstatus'), nullable=False),
    sa.Column('action', sa.Enum('answer', 'tbd', 'out_of_scope', name='tbdaction'), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clarifications_project_id', 'clarifications', ['project_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('upload_ts', sa.DateTime(), nullable=False),
    sa.Column('anonymized_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'anonymising', 'ready', name='documentstatus'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_project_id', 'documents', ['project_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'skill_id'),
    sa.UniqueConstraint('employee_id', 'skill_id')
    )
    op.create_index('ix_employee_skills_employee_id', 'employee_skills', ['employee_id'], unique=False)
    op.create_index('ix_employee_skills_skill_id', 'employee_skills', ['skill_id'], unique=False)
    op.create_table('epics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_points', sa.Integer(), nullable=True),
    sa.Column('github_milestone_number', sa.Integer(), nullable=True),
    sa.Column('github_milestone_url', sa.String(length=500), nullable=True),
    sa.Column('sync_status', sa.Enum('pending', 'synced', 'skipped', 'failed', name='syncstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_epics_project_id', 'epics', ['project_id'], unique=False)
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=100), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_error_logs_project_id', 'error_logs', ['project_id'], unique=False)
    op.create_table('latency_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_latency_logs_project_id', 'latency_logs', ['project_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metrics_project_id', 'metrics', ['project_id'], unique=False)
    op.create_table('proposal_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index('ix_proposal_state_project_id', 'proposal_state', ['project_id'], unique=False)
    op.create_table('pii_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('text_original', sa.String(length=1000), nullable=False),
    sa.Column('text_replacement', sa.String(length=1000), nullable=False),
    sa.Column('pii_type', sa.String(length=100), nullable=False),
    sa.Column('detection_method', sa.String(length=10), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('overridden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pii_detections_document_id', 'pii_detections', ['document_id'], unique=False)
    op.create_table('pii_ingestion_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pii_ingestion_logs_document_id', 'pii_ingestion_logs', ['document_id'], unique=False)
    op.create_index('ix_pii_ingestion_logs_project_id', 'pii_ingestion_logs', ['project_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('content_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposals_document_id', 'proposals', ['document_id'], unique=False)
    op.create_index('ix_proposals_project_id', 'proposals', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('epic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_points', sa.Integer(), nullable=True),
    sa.Column('github_issue_number', sa.Integer(), nullable=True),
    sa.Column('github_issue_url', sa.String(length=500), nullable=True),
    sa.Column('sync_status', sa.Enum('pending', 'synced', 'skipped', 'failed', name='syncstatus'), nullable=False),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('assignees', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_epic_id', 'tasks', ['epic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Observability (no FK to other app tables — project_id is nullable or soft)
    op.drop_index('ix_error_logs_project_id', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index('ix_latency_logs_project_id', table_name='latency_logs')
    op.drop_table('latency_logs')
    op.drop_index('ix_metrics_project_id', table_name='metrics')
    op.drop_table('metrics')
    # PII (depends on documents)
    op.drop_index('ix_pii_ingestion_logs_project_id', table_name='pii_ingestion_logs')
    op.drop_index('ix_pii_ingestion_logs_document_id', table_name='pii_ingestion_logs')
    op.drop_table('pii_ingestion_logs')
    op.drop_index('ix_pii_detections_document_id', table_name='pii_detections')
    op.drop_table('pii_detections')
    # Sync (tasks → epics → projects)
    op.drop_index('ix_tasks_epic_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_epics_project_id', table_name='epics')
    op.drop_table('epics')
    # Reference (no FK deps)
    op.drop_table('historical_projects')
    op.drop_table('approved_technologies')
    # Employee
    op.drop_index('ix_employee_skills_employee_id', table_name='employee_skills')
    op.drop_index('ix_employee_skills_skill_id', table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_table('employees')
    op.drop_table('skills')
    # Clarifications (depends on projects)
    op.drop_index('ix_clarifications_project_id', table_name='clarifications')
    op.drop_table('clarifications')
    # Project group (proposals/docs before project)
    op.drop_index('ix_proposal_state_project_id', table_name='proposal_state')
    op.drop_table('proposal_state')
    op.drop_index('ix_proposals_project_id', table_name='proposals')
    op.drop_index('ix_proposals_document_id', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('ix_documents_project_id', table_name='documents')
    op.drop_table('documents')
    op.drop_table('projects')
